#!/bin/bash
srcdir="$(dirname "$(readlink -f "$0")")"
echo "$srcdir"
docker run \
    -v "$srcdir"/configdb:/data/configdb \
    -v "$srcdir"/db:/data/db \
    -p 27017:27017 \
    --name mongo -d my/mongo \
